connection.execute("""INSERT INTO genre(title) VALUES('POP');""")
connection.execute("""INSERT INTO genre(title) VALUES('RAP');""")
connection.execute("""INSERT INTO genre(title) VALUES('Rock');""")
connection.execute("""INSERT INTO genre(title) VALUES('Blues');""")
connection.execute("""INSERT INTO genre(title) VALUES('Classic');""")
connection.execute("""INSERT INTO genre(title) VALUES('Folk');""")
connection.execute("""INSERT INTO genre(title) VALUES('Metall');""")
connection.execute("""INSERT INTO genre(title) VALUES('Dance');""")
connection.execute("""INSERT INTO genre(title) VALUES('Club');""")

connection.execute("""INSERT INTO singer(singer_name, alias) VALUES('Сергей Круппов', 'ATL');""")
connection.execute("""INSERT INTO singer(singer_name, alias) VALUES('Адиль Жале́лов', 'Скриптонит');""")
connection.execute("""INSERT INTO singer(singer_name, alias) VALUES('Филипп Киркоров', 'Филипп Киркоров');""")
connection.execute("""INSERT INTO singer(singer_name, alias) VALUES('Марина Жада́н', 'Мари Краймбрери');""")
connection.execute("""INSERT INTO singer(singer_name, alias) VALUES('Виктор Цой', 'Виктор Цой');""")
connection.execute("""INSERT INTO singer(singer_name, alias) VALUES('Вольфганг Моцарт', 'Mozart');""")
connection.execute("""INSERT INTO singer(singer_name, alias) VALUES('Наталья О’Шей', 'Хелависа');""")
connection.execute("""INSERT INTO singer(singer_name, alias) VALUES('Тилль Ли́ндеманн', 'Lindemann');""")
connection.execute("""INSERT INTO singer(singer_name, alias) VALUES('Роберт Лерой Джонсон', 'Роберт Лерой Джонсон');""")

connection.execute("""INSERT INTO singergenge(singer, genge) VALUES(1,2);""")
connection.execute("""INSERT INTO singergenge(singer, genge) VALUES(1,9);""")
connection.execute("""INSERT INTO singergenge(singer, genge) VALUES(2,2);""")
connection.execute("""INSERT INTO singergenge(singer, genge) VALUES(2,8);""")
connection.execute("""INSERT INTO singergenge(singer, genge) VALUES(3,1);""")
connection.execute("""INSERT INTO singergenge(singer, genge) VALUES(4,1);""")
connection.execute("""INSERT INTO singergenge(singer, genge) VALUES(4,9);""")
connection.execute("""INSERT INTO singergenge(singer, genge) VALUES(5,3);""")
connection.execute("""INSERT INTO singergenge(singer, genge) VALUES(6,5);""")
connection.execute("""INSERT INTO singergenge(singer, genge) VALUES(7,6);""")
connection.execute("""INSERT INTO singergenge(singer, genge) VALUES(8,7);""")
connection.execute("""INSERT INTO singergenge(singer, genge) VALUES(9,4);""")

connection.execute("""INSERT INTO album(title, year_of_creation) VALUES('Марабу', 2015);""")
connection.execute("""INSERT INTO album(title, year_of_creation) VALUES('Уроборос', 2017,);""")
connection.execute("""INSERT INTO album(title, year_of_creation) VALUES('Переобулась', 2018);""")
connection.execute("""INSERT INTO album(title, year_of_creation) VALUES('Ленинград', 1984);""")
connection.execute("""INSERT INTO album(title, year_of_creation) VALUES('Symph38', 1787);""")
connection.execute("""INSERT INTO album(title, year_of_creation) VALUES('Зов крови', 2006);""")
connection.execute("""INSERT INTO album(title, year_of_creation) VALUES('Mutter', 2001);""")
connection.execute("""INSERT INTO album(title, year_of_creation) VALUES('Sugar Mama Blues', 2009);""")
connection.execute("""INSERT INTO album(title, year_of_creation) VALUES('Ты поверишь', 2001);""")

connection.execute("""INSERT INTO albumsinger(singer, album) VALUES(1,1);""")
connection.execute("""INSERT INTO albumsinger(singer, album) VALUES(2,2);""")
connection.execute("""INSERT INTO albumsinger(singer, album) VALUES(4,3);""")
connection.execute("""INSERT INTO albumsinger(singer, album) VALUES(5,4);""")
connection.execute("""INSERT INTO albumsinger(singer, album) VALUES(6,5);""")
connection.execute("""INSERT INTO albumsinger(singer, album) VALUES(7,6);""")
connection.execute("""INSERT INTO albumsinger(singer, album) VALUES(8,7);""")
connection.execute("""INSERT INTO albumsinger(singer, album) VALUES(9,8);""")
connection.execute("""INSERT INTO albumsinger(singer, album) VALUES(3,9);""")

connection.execute("""INSERT INTO song(title, duration, id_album) VALUES('Удобрением', 152, 1);""")
connection.execute("""INSERT INTO song(title, duration, id_album) VALUES('Марабу', 153, 1);""")
connection.execute("""INSERT INTO song(title, duration, id_album) VALUES('Искра', 220, 1);""")

connection.execute("""INSERT INTO song(title, duration, id_album) VALUES('Животные', 182, 2);""")
connection.execute("""INSERT INTO song(title, duration, id_album) VALUES('Мистер 817', 226, 2);""")
connection.execute("""INSERT INTO song(title, duration, id_album) VALUES('Пацан', 157, 2);""")

connection.execute("""INSERT INTO song(title, duration, id_album) VALUES('Бой', 240, 3);""")
connection.execute("""INSERT INTO song(title, duration, id_album) VALUES('Том и Джерри', 211, 3);""")
connection.execute("""INSERT INTO song(title, duration, id_album) VALUES('Палево', 225, 3);""")

connection.execute("""INSERT INTO song(title, duration, id_album) VALUES('Весна', 158, 4);""")
connection.execute("""INSERT INTO song(title, duration, id_album) VALUES('Последний герой', 111, 4);""")
connection.execute("""INSERT INTO song(title, duration, id_album) VALUES('Гопники', 202, 4);""")

connection.execute("""INSERT INTO song(title, duration, id_album) VALUES('Двери Тамерлана', 209, 6);""")
connection.execute("""INSERT INTO song(title, duration, id_album) VALUES('Травушка', 189, 6);""")
connection.execute("""INSERT INTO song(title, duration, id_album) VALUES('Дракон', 210, );""")

connection.execute("""INSERT INTO song(title, duration, id_album) VALUES('Ты повершь', 240, 9);""")
connection.execute("""INSERT INTO song(title, duration, id_album) VALUES('Дива', 210, 6);""")
connection.execute("""INSERT INTO song(title, duration, id_album) VALUES('Огонь и вода', 215 , 6);""")

connection.execute("""INSERT INTO collection(title, year_of_creation) VALUES('Hit of 18 century',1950);""")
connection.execute("""INSERT INTO collection(title, year_of_creation) VALUES('Hit of 80's',1990);""")
connection.execute("""INSERT INTO collection(title, year_of_creation) VALUES('Hit of 90's',2000);""")
connection.execute("""INSERT INTO collection(title, year_of_creation) VALUES('Hit of 2000's', 2005);""")
connection.execute("""INSERT INTO collection(title, year_of_creation) VALUES('Hit of 2010's', 2011);""")
connection.execute("""INSERT INTO collection(title, year_of_creation) VALUES('Hit of 2020's', 2021);""")
connection.execute("""INSERT INTO collection(title, year_of_creation) VALUES('Top 100. World', 2022);""")
connection.execute("""INSERT INTO collection(title, year_of_creation) VALUES('Top 100. Russia', 2020);""")

connection.execute("""INSERT INTO songcollection(song,collection) VALUES(1,8)""")
connection.execute("""INSERT INTO songcollection(song,collection) VALUES(2,8)""")
connection.execute("""INSERT INTO songcollection(song,collection) VALUES(3,8)""")
connection.execute("""INSERT INTO songcollection(song,collection) VALUES(1,7)""")
connection.execute("""INSERT INTO songcollection(song,collection) VALUES(2,7)""")
connection.execute("""INSERT INTO songcollection(song,collection) VALUES(3,6)""")
connection.execute("""INSERT INTO songcollection(song,collection) VALUES(4,6)""")
connection.execute("""INSERT INTO songcollection(song,collection) VALUES(5,6)""")
connection.execute("""INSERT INTO songcollection(song,collection) VALUES(6,5)""")
connection.execute("""INSERT INTO songcollection(song,collection) VALUES(7,5)""")
connection.execute("""INSERT INTO songcollection(song,collection) VALUES(8,5)""")
connection.execute("""INSERT INTO songcollection(song,collection) VALUES(9,4)""")
connection.execute("""INSERT INTO songcollection(song,collection) VALUES(4,5)""")
connection.execute("""INSERT INTO songcollection(song,collection) VALUES(5,5)""")
connection.execute("""INSERT INTO songcollection(song,collection) VALUES(6,6)""")
connection.execute("""INSERT INTO songcollection(song,collection) VALUES(7,6)""")
connection.execute("""INSERT INTO songcollection(song,collection) VALUES(8,4)""")
connection.execute("""INSERT INTO songcollection(song,collection) VALUES(9,3)""")
connection.execute("""INSERT INTO songcollection(song,collection) VALUES(7,3)""")
connection.execute("""INSERT INTO songcollection(song,collection) VALUES(8,3)""")
connection.execute("""INSERT INTO songcollection(song,collection) VALUES(9,3)""")
connection.execute("""INSERT INTO songcollection(song,collection) VALUES(10,3)""")
connection.execute("""INSERT INTO songcollection(song,collection) VALUES(11,3)""")
connection.execute("""INSERT INTO songcollection(song,collection) VALUES(12,3)""")
connection.execute("""INSERT INTO songcollection(song,collection) VALUES(7,4)""")
connection.execute("""INSERT INTO songcollection(song,collection) VALUES(8,2)""")
connection.execute("""INSERT INTO songcollection(song,collection) VALUES(9,2)""")
connection.execute("""INSERT INTO songcollection(song,collection) VALUES(10,4)""")
connection.execute("""INSERT INTO songcollection(song,collection) VALUES(11,8)""")
connection.execute("""INSERT INTO songcollection(song,collection) VALUES(12,7)""")
connection.execute("""INSERT INTO songcollection(song,collection) VALUES(13,6)""")
connection.execute("""INSERT INTO songcollection(song,collection) VALUES(14,5)""")
connection.execute("""INSERT INTO songcollection(song,collection) VALUES(15,3)""")
connection.execute("""INSERT INTO songcollection(song,collection) VALUES(16,4)""")
connection.execute("""INSERT INTO songcollection(song,collection) VALUES(17,5)""")
connection.execute("""INSERT INTO songcollection(song,collection) VALUES(18,8)""")

print(connection.execute("""SELECT title, year_of_creation FROM album WHERE year_of_creation=2018;""").fetchall())
print(connection.execute("""SELECT title, duration FROM song ORDER BY duration DESC LIMIT 1;""").fetchall())
print(connection.execute("""SELECT title FROM song WHERE duration >= 210;""").fetchall())
print(connection.execute("""SELECT title FROM song WHERE duration >= 210;""").fetchall())
print(connection.execute("""SELECT title FROM collection WHERE year_of_creation >= 2018 and year_of_creation <= 2020;""").fetchall())
print(connection.execute("""SELECT singer_name FROM singer WHERE alias NOT LIKE '%% %%';""").fetchall())
print(connection.execute("""SELECT title FROM song WHERE title LIKE '%%герой%%';""").fetchall())